import { collection, config, fields, singleton } from "@keystatic/core";

const githubStorage = { kind: "github" as const, repo: "asterunee/Blog" as const, branchPrefix: "content/" };
const localStorage = { kind: "local" as const };
export const keystaticGithubMode = process.env.NEXT_PUBLIC_KEYSTATIC_STORAGE === "github";

const required = { validation: { isRequired: true } } as const;
const today = { kind: "today" as const };
const richEditorOptions = {
  bold: true,
  italic: true,
  strikethrough: true,
  code: true,
  heading: [2, 3, 4, 5, 6] as const,
  blockquote: true,
  orderedList: true,
  unorderedList: true,
  table: true,
  link: true,
  divider: true,
  codeBlock: true,
};

const bodyField = (directory: string, publicPath: string, description: string) => fields.mdx({
  label: "본문",
  description,
  options: {
    ...richEditorOptions,
    image: {
      directory,
      publicPath,
      schema: {
        alt: fields.text({ label: "대체 텍스트", description: "접근성을 위해 이미지 내용을 설명하세요." }),
        title: fields.text({ label: "이미지 제목" }),
      },
    },
  },
});

export default config({
  storage: keystaticGithubMode ? githubStorage : localStorage,
  ui: {
    brand: { name: "asterunee studio" },
    navigation: {
      "글 작성": ["posts", "solutions", "logs"],
      "블로그 관리": ["site"],
    },
  },
  collections: {
    posts: collection({
      label: "일반 글",
      slugField: "title",
      path: "content/posts/*",
      entryLayout: "content",
      previewUrl: "/posts/{slug}",
      columns: ["title", "category", "date", "pinned", "draft"],
      format: { contentField: "body" },
      schema: {
        title: fields.slug({ name: { label: "글 제목", validation: { isRequired: true } }, slug: { label: "URL slug", description: "영문 소문자와 하이픈을 권장합니다." } }),
        description: fields.text({ label: "글 요약", multiline: true, description: "목록과 공유 카드에 표시됩니다.", ...required }),
        category: fields.text({ label: "카테고리", description: "원하는 이름을 직접 입력하세요. 예: 개발, 여행, 음악", defaultValue: "미분류", ...required }),
        series: fields.text({ label: "시리즈", description: "연재가 아니라면 비워 두세요." }),
        tags: fields.array(fields.text({ label: "태그" }), { label: "태그", itemLabel: (props) => props.value }),
        date: fields.date({ label: "작성일", defaultValue: today, ...required }),
        updated: fields.date({ label: "수정일", defaultValue: today, ...required }),
        author: fields.text({ label: "작성자", defaultValue: "asterunee", ...required }),
        coverImage: fields.image({ label: "표지 이미지", description: "목록과 글 상단에 사용됩니다.", directory: "public/images/posts", publicPath: "/images/posts/" }),
        coverAlt: fields.text({ label: "표지 이미지 설명", description: "이미지가 있을 때 작성하세요." }),
        accentColor: fields.text({ label: "글 강조 색", description: "비우면 사이트 기본 색을 사용합니다. 예: #7dd3fc", validation: { pattern: { regex: /^$|^#[0-9a-fA-F]{6}$/, message: "#RRGGBB 형식으로 입력하세요." } } }),
        seoTitle: fields.text({ label: "검색용 제목", description: "비우면 글 제목을 사용합니다." }),
        seoDescription: fields.text({ label: "검색용 설명", multiline: true, description: "비우면 글 요약을 사용합니다." }),
        canonicalUrl: fields.text({ label: "원문 URL", description: "다른 곳에서 먼저 발행한 글만 입력하세요." }),
        showToc: fields.checkbox({ label: "목차 표시", defaultValue: true }),
        featured: fields.checkbox({ label: "대표 글", defaultValue: false }),
        pinned: fields.checkbox({ label: "목록 상단 고정", defaultValue: false }),
        draft: fields.checkbox({ label: "초안", description: "해제한 글만 운영 사이트에 공개됩니다.", defaultValue: true }),
        body: bodyField("public/images/posts", "/images/posts/", "제목, 표, 인용문, 링크, 코드 블록과 이미지를 자유롭게 사용할 수 있습니다."),
      },
    }),
    solutions: collection({
      label: "PS 풀이",
      slugField: "title",
      path: "content/solutions/*",
      entryLayout: "content",
      previewUrl: "/solutions/{slug}",
      columns: ["title", "judge", "problemId", "date", "draft"],
      format: { contentField: "body" },
      schema: {
        title: fields.slug({ name: { label: "풀이 제목", validation: { isRequired: true } }, slug: { label: "URL slug", description: "영문 소문자와 하이픈을 권장합니다." } }),
        description: fields.text({ label: "풀이 요약", multiline: true, ...required }),
        date: fields.date({ label: "작성일", defaultValue: today, ...required }),
        updated: fields.date({ label: "수정일", defaultValue: today, ...required }),
        author: fields.text({ label: "작성자", defaultValue: "asterunee", ...required }),
        judge: fields.text({ label: "온라인 저지", defaultValue: "Codeforces", ...required }),
        contest: fields.text({ label: "대회/라운드" }),
        problemId: fields.text({ label: "문제 번호", ...required }),
        problemUrl: fields.url({ label: "문제 원문 URL", ...required }),
        difficulty: fields.integer({ label: "레이팅/예상 난이도", defaultValue: 0, validation: { isRequired: true, min: 0, max: 10000 } }),
        tier: fields.text({ label: "티어 표기", defaultValue: "Unrated", ...required }),
        solutionType: fields.text({ label: "풀이 유형", description: "예: 정규 풀이, 업솔빙, 다른 풀이" }),
        status: fields.text({ label: "상태", defaultValue: "Solved", ...required }),
        language: fields.text({ label: "언어", defaultValue: "C++17", ...required }),
        tags: fields.array(fields.text({ label: "태그" }), { label: "알고리즘 태그", itemLabel: (props) => props.value }),
        solveTime: fields.integer({ label: "풀이 시간(분)", defaultValue: 1, validation: { isRequired: true, min: 1 } }),
        timeLimit: fields.text({ label: "시간 제한", defaultValue: "2 seconds", ...required }),
        memoryLimit: fields.text({ label: "메모리 제한", defaultValue: "256 MB", ...required }),
        runtime: fields.text({ label: "실행 시간" }),
        memoryUsed: fields.text({ label: "사용 메모리" }),
        coverImage: fields.image({ label: "대표 이미지", directory: "public/images/solutions", publicPath: "/images/solutions/" }),
        coverAlt: fields.text({ label: "대표 이미지 설명" }),
        featured: fields.checkbox({ label: "대표 풀이", defaultValue: false }),
        draft: fields.checkbox({ label: "초안", description: "해제한 풀이만 운영 사이트에 공개됩니다.", defaultValue: true }),
        body: bodyField("public/images/solutions", "/images/solutions/", "관찰, 도출 과정, 증명, 복잡도, 구현과 디버깅을 기록하세요."),
      },
    }),
    logs: collection({
      label: "짧은 기록",
      slugField: "title",
      path: "content/log/*",
      entryLayout: "content",
      previewUrl: "/log/{slug}",
      columns: ["title", "type", "date", "featured", "draft"],
      format: { contentField: "body" },
      schema: {
        title: fields.slug({ name: { label: "기록 제목", validation: { isRequired: true } }, slug: { label: "URL slug" } }),
        description: fields.text({ label: "기록 요약", multiline: true, ...required }),
        type: fields.text({ label: "기록 종류", description: "원하는 분류를 직접 입력하세요.", defaultValue: "메모", ...required }),
        mood: fields.text({ label: "기분/상태" }),
        location: fields.text({ label: "장소" }),
        tags: fields.array(fields.text({ label: "태그" }), { label: "태그", itemLabel: (props) => props.value }),
        date: fields.date({ label: "작성일", defaultValue: today, ...required }),
        updated: fields.date({ label: "수정일", defaultValue: today, ...required }),
        author: fields.text({ label: "작성자", defaultValue: "asterunee", ...required }),
        coverImage: fields.image({ label: "기록 이미지", directory: "public/images/log", publicPath: "/images/log/" }),
        coverAlt: fields.text({ label: "이미지 설명" }),
        featured: fields.checkbox({ label: "대표 기록", defaultValue: false }),
        draft: fields.checkbox({ label: "초안", defaultValue: true }),
        body: bodyField("public/images/log", "/images/log/", "짧은 메모부터 긴 회고까지 자유롭게 작성하세요."),
      },
    }),
  },
  singletons: {
    site: singleton({
      label: "사이트 설정",
      path: "content/settings/site",
      entryLayout: "form",
      format: "json",
      previewUrl: "/",
      schema: {
        siteName: fields.text({ label: "블로그 이름", ...required }),
        tagline: fields.text({ label: "메인 제목", ...required }),
        description: fields.text({ label: "사이트 설명", multiline: true, ...required }),
        intro: fields.text({ label: "홈 소개 문장", multiline: true, ...required }),
        sidebarIntro: fields.text({ label: "사이드바 소개", multiline: true, ...required }),
        motto: fields.text({ label: "짧은 문구", ...required }),
        supportingLine: fields.text({ label: "보조 문구", ...required }),
        role: fields.text({ label: "소개 역할", ...required }),
        nowTitle: fields.text({ label: "현재 관심사 제목", description: "비우면 홈의 현재 관심사 위젯을 숨깁니다." }),
        nowDescription: fields.text({ label: "현재 관심사 설명", multiline: true }),
        backgroundImage: fields.image({ label: "사이트 배경 이미지", description: "기존 이미지 또는 새 이미지를 업로드할 수 있습니다.", directory: "public/images", publicPath: "/images/" }),
        backgroundPosition: fields.select({ label: "배경 위치", options: [{ label: "가운데", value: "center" }, { label: "왼쪽", value: "left" }, { label: "오른쪽", value: "right" }, { label: "위", value: "top" }, { label: "아래", value: "bottom" }], defaultValue: "center" }),
        backgroundStrength: fields.integer({ label: "배경 이미지 강도(%)", defaultValue: 16, validation: { isRequired: true, min: 0, max: 60 } }),
        backgroundPattern: fields.select({ label: "배경 효과", options: [{ label: "별빛", value: "stars" }, { label: "오로라", value: "aurora" }, { label: "잔잔함", value: "quiet" }, { label: "효과 없음", value: "none" }], defaultValue: "stars" }),
        accentColor: fields.text({ label: "사이트 강조 색", description: "#RRGGBB 형식", defaultValue: "#5ee7f7", validation: { isRequired: true, pattern: { regex: /^#[0-9a-fA-F]{6}$/, message: "#RRGGBB 형식으로 입력하세요." } } }),
        defaultTheme: fields.select({ label: "기본 테마", options: [{ label: "별밤", value: "dark" }, { label: "오로라", value: "aurora" }, { label: "숲", value: "forest" }, { label: "노을", value: "sunset" }, { label: "종이", value: "paper" }, { label: "밝게", value: "light" }], defaultValue: "dark" }),
        showJudgeSignals: fields.checkbox({ label: "홈에 PS 활동 표시", defaultValue: true }),
      },
    }),
  },
});
